// WebSocket Event Constants
export const SOCKET_EVENTS = {
  REVENUE_UPDATE: 'REVENUE_UPDATE',
  ATTENDANCE_UPDATE: 'ATTENDANCE_UPDATE',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  MEMBER_CREATED: 'MEMBER_CREATED',
  MEMBER_UPDATED: 'MEMBER_UPDATED',
  MEMBER_DELETED: 'MEMBER_DELETED',
  NEW_NOTIFICATION: 'NEW_NOTIFICATION',
  BRANCH_STATS_UPDATED: 'BRANCH_STATS_UPDATED',
};
